FROM ubuntu:16.04

## Python installation ##
RUN apt-get update && apt-get install -y python3 python3-pip python3-numpy python3-yaml pkg-config libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev libx264-dev libwebp-dev zlib1g-dev libjpeg-dev libpng-dev libtiff5-dev libjasper-dev git vim wget unzip cmake openssh-server screen ffmpeg && apt-get clean

# Maybe required in a near future...
# apt-get -y install build-essential qt5-default libvtk6-dev zlib1g-dev libjpeg-dev libpng-dev libtiff5-dev libjasper-dev libopenexr-dev libgdal-dev libdc1394-22-dev libtheora-dev libvorbis-dev yasm libopencore-amrnb-dev libopencore-amrwb-dev libv4l-dev libxine2-dev python-dev python-tk python-numpy python3-dev python3-tk libgtk2.0-dev

## Download and compile OpenCV 3.4.0 ##
RUN cd / && wget https://github.com/opencv/opencv/archive/3.4.0.zip && unzip 3.4.0.zip && cd /opencv-3.4.0 && mkdir build && cd build && cmake -DBUILD_EXAMPLES=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DWITH_CUDA=OFF -DWITH_OPENCL=OFF -DCMAKE_BUILD_TYPE=RELEASE -DINSTALL_C_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_PROTOBUF=OFF -DBUILD_WITH_DEBUG_INFO=OFF -DBUILD_DOCS=OFF -DBUILD_PACKAGE=OFF -DWITH_V4L=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_IPP_IW=OFF -DBUILD_ITT=OFF -DCV_TRACE=OFF -DCV_ENABLE_INTRINSICS=OFF -DWITH_ITT=OFF -DWITH_IPP=OFF .. && make -j9 install && make clean && rm -r /3.4.0.zip /opencv-3.4.0 && ldconfig

## Downloading and compiling darknet ##
RUN cd / && git clone https://github.com/vgarcia-visionaip/darknet.git && cd /darknet && sed -i -e 's/OPENCV=0/OPENCV=1/' -e 's/rm -rf $(OBJS) $(SLIB) $(ALIB) $(EXEC)/rm -rf $(OBJS) $(ALIB)/' Makefile && make -j9 && make clean && echo '/darknet' > /etc/ld.so.conf.d/darknet.conf && ldconfig
ENV DARKNET_HOME /darknet

## Compile YOLO3-4-Py ##
COPY cdc /darknet
RUN cd /darknet && pip3 install cython python-keycloak && pip3 install -e .

COPY . /custom_detector
## Test command line
WORKDIR /custom_detector
