FROM nvidia/cuda:9.1-devel-ubuntu16.04

## Python3, ffmpeg libraries, git, cmake, etc. installation ##
RUN apt-get update && apt-get install -y python3 python3-pip python3-numpy python3-yaml pkg-config libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev libx264-dev libwebp-dev zlib1g-dev libjpeg-dev libpng-dev libtiff5-dev libjasper-dev git wget unzip cmake openssh-server screen ffmpeg && apt-get clean

## Install BCP #
RUN git clone https://gitlab.com:-zsLzxCP1T1RrhUcx-1H@gitlab.com/NRG-5/NFV/VNFs/vbcp/vBCP-client.git vbcp-client && cd /vbcp-client && pip3 install dist/vbcp_client-1.1.tar.gz

## Download and compile OpenCV 3.4.0 ##
RUN cd / && wget https://github.com/opencv/opencv/archive/3.4.0.zip && unzip 3.4.0.zip && cd /opencv-3.4.0 && mkdir build && cd build && cmake -DBUILD_EXAMPLES=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DWITH_CUDA=OFF -DWITH_OPENCL=OFF -DCMAKE_BUILD_TYPE=RELEASE -DINSTALL_C_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_PROTOBUF=OFF -DBUILD_WITH_DEBUG_INFO=OFF -DBUILD_DOCS=OFF -DBUILD_PACKAGE=OFF -DWITH_V4L=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_calib3d=OFF .. && make -j9 install && make clean && rm -r /3.4.0.zip /opencv-3.4.0

## Downloading and compiling darknet with opencv 3.4.0 ##
RUN cd / && git clone https://github.com/vgarcia-visionaip/darknet.git && cd /darknet && sed -i -e 's/OPENCV=0/OPENCV=1/' -e 's/GPU=0/GPU=1/' Makefile && make -j9 && echo '/darknet' > /etc/ld.so.conf.d/darknet.conf && ldconfig
# Required by pydarknet pip3 local install
ENV DARKNET_HOME=/darknet CUDA_HOME=/usr/local/cuda

# Compile YOLO3-4-Py ##
COPY cdg /darknet
RUN cd /darknet && pip3 install cython python-keycloak && pip3 install -e .

COPY . /custom_detector
## Test command line
WORKDIR /custom_detector
